### PR TITLE
C2: Login: Still working on how to write to a file with json

### PR DESCRIPTION
**Pull request by christopherchay**
Temporary review. Not finished yet.

### CODE REVIEW

**Comment by EmmanuelChay** [comment]
Can i see your code??

**Review by cchay — CHANGES_REQUESTED** [review]
The variable names do not make sense.  What is FlameWright mean?

The comments need to be accurate.  "Changing json to python" is incorrectd.  Json is a data structure and python is the programming language.

Please make these changes before resubmitting.

**Comment by christopherchay** [comment]
I deleted the unnecessary comments and I changed the variable 'FlameWright' to 'user'.

**Comment by celestachay** [comment]
I can't run it!
(~~~
(~~~  /

**Review by celestachay — APPROVED** [review]

**Review by EmmanuelChay — APPROVED** [review]

**Review by cchay — APPROVED** [review]
I see the changes that I requested.  OK to go ahead with merging to master.

**Comment by celestachay** [comment]
WHAT DO YOU WANT////?????

**Pull request merged**
